name: website-cd
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: us-east-1
  APPLICATION: website
  NAMESPACE: website
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789:role/github-actions
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      - name: Config kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name eks-dev --kubeconfig ./kubeconfig
      - name: Helm install
        uses: ./.github/actions/kubectl-helm
        with:
          run: |
            kubectl create namespace ${{ env.NAMESPACE }}
            helm upgrade --install ${{ env.APPLICATION }} --namespace ${{ env.NAMESPACE }} --set tag=${{ github.sha }} helm-chart/${{ env.APPLICATION }}/
